- name: disable selinux
  selinux:
    policy=targeted
    state=disabled
  notify:
    - restart server
    - wait for server to restart

- name: disable iptables
  service:
    name=iptables
    state=stopped
    enabled=no
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

#- name: disable firewalld
#  service:
#    name=firewalld
#    state=stopped
#    enabled=no
#  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: install packages linux 6
  yum:
    name={{ item }}
    state=present
  with_items:
    - binutils
    - compat-libcap1
    - compat-libstdc++-33
    - gcc
    - gcc-c++
    - glibc
    - glibc-devel
    - ksh
    - libaio
    - libaio-devel
    - libgcc
    - libstdc++
    - libstdc++-devel
    - libxcb
    - libX11
    - libXau
    - libXext
    - libXi
    - libXtst
    - make
    - sysstat
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

- name: Install wget package
  action: yum name='wget' state=installed

- name: Download public-yum-el7.repo
    get_url:
      url: http://public-yum.oracle.com/public-yum-ol7.repo
      dest: /etc/yum.repos.d/public-yum-el7.repo
      mode: 0750

- name: Download RPM-GPG-KEY-oracle-ol7
  get_url:
    url: http://public-yum.oracle.com/RPM-GPG-KEY-oracle-ol7
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
    mode: 0750

- name: install pre-reqs
  yum:
    name: oracle-rdbms-server-12cR1-preinstall
    state: present


- name: User | Add group(s)
  group:
    name={{ item.group }}
    gid={{ item.gid }}
    state=present
  with_items:
    - { group: asmdba, gid: 54318 }
    - { group: asmoper, gid: 54319 }
    - { group: asmadmin, gid: 54320 }
    - { group: oinstall, gid: 54321 }
    - { group: dba, gid: 54322 }
    - { group: backupdba, gid: 54323 }
    - { group: oper, gid: 54324 }
    - { group: dgdba, gid: 54325 }
    - { group: kmdba, gid: 54326 }
    -  {group: ansible, gid: 1001}


- name: create user
  user: name={{ item.username }}  group={{ item.primgroup }} groups={{ item.othergroups }} uid={{ item.uid }}  state=present password={{ oracle_install_password }}
  with_items:
    - { username: oracle, uid: 54321, primgroup: oinstall, othergroups: "dba,asmdba,backupdba,dgdba,kmdba,oper,asmadmin,asmdba,asmoper,dba" }

- template:
    src=database_common/templates/linux/sysctl_conf.j2
    dest=/etc/sysctl.conf
    owner=root
    group=root
    mode=0644

- template:
    src=database_common/templates/linux/limits_conf.j2
    dest=/etc/security/limits.conf
    owner=root
    group=root
    mode=0644
